#!/bin/sh

screenfetch -A 'Antergos'
echo 'Antergos'
screenfetch -A 'Arch  Linux'
echo 'Arch  Linux'
screenfetch -A 'BLAG'
echo 'BLAG'
screenfetch -A 'CentOS'
echo 'CentOS'
screenfetch -A 'Chakra'
echo 'Chakra'
screenfetch -A 'Chapeau'
echo 'Chapeau'
screenfetch -A 'CrunchBang'
echo 'CrunchBang'
screenfetch -A 'CRUX'
echo 'CRUX'
screenfetch -A 'Debian'
echo 'Debian'
screenfetch -A 'Deepin'
echo 'Deepin'
screenfetch -A 'Dragora'
echo 'Dragora'
screenfetch -A 'elementary OS'
echo 'elementary OS'
screenfetch -A 'Evolve OS'
echo 'Evolve OS'
screenfetch -A 'Fedora'
echo 'Fedora'
screenfetch -A 'Frugalware'
echo 'Frugalware'
screenfetch -A 'Fuduntu'
echo 'Fuduntu'
screenfetch -A 'Funtoo'
echo 'Funtoo'
screenfetch -A 'Gentoo'
echo 'Gentoo'
screenfetch -A 'gNewSense'
echo 'gNewSense'
screenfetch -A 'Jiyuu Linux'
echo 'Jiyuu Linux'
screenfetch -A 'Kali Linux'
echo 'Kali Linux'
screenfetch -A 'KaOS'
echo 'KaOS'
screenfetch -A 'Korora'
echo 'Korora'
screenfetch -A 'LinuxDeepin'
echo 'LinuxDeepin'
screenfetch -A 'Mint'
echo 'Mint'
screenfetch -A 'LMDE'
echo 'LMDE'
screenfetch -A 'Logos'
echo 'Logos'
screenfetch -A 'Mageia'
echo 'Mageia'
screenfetch -A 'Mandriva/Mandrake'
echo 'Mandriva/Mandrake'
screenfetch -A 'Manjaro'
echo 'Manjaro'
screenfetch -A 'NixOS'
echo 'NixOS'
screenfetch -A 'openSUSE'
echo 'openSUSE'
screenfetch -A 'Parabola GNU/Linux-libre'
echo 'Parabola GNU/Linux-libre'
screenfetch -A 'PeppermintOS'
echo 'PeppermintOS'
screenfetch -A 'Raspbian'
echo 'Raspbian'
screenfetch -A 'Red Hat Enterprise Linux'
echo 'Red Hat Enterprise Linux'
screenfetch -A 'Sabayon'
echo 'Sabayon'
screenfetch -A 'Scientific Linux'
echo 'Scientific Linux'
screenfetch -A 'Slackware'
echo 'Slackware'
screenfetch -A 'SolusOS'
echo 'SolusOS'
screenfetch -A 'TinyCore'
echo 'TinyCore'
screenfetch -A 'Trisquel'
echo 'Trisquel'
screenfetch -A 'Ubuntu'
echo 'Ubuntu'
screenfetch -A 'Viperr'
echo 'Viperr'
screenfetch -A 'Void'
echo 'Void'
